apiVersion: v1
kind: Service
metadata:
  name: springboot-docker-integration-service
spec:
  type: LoadBalancer
  selector:
    app: springboot-docker-integration-deployment-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
